apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: jenkins-ingress-resource
spec:
  rules:
  - host: jenkins.wizen.com
    http:
      paths:
      - backend:
          serviceName: nginx-deploy-main
          servicePort: 80
